version: '3'

networks:
  immobrnet:
    driver: bridge

services:
  immobr:
    build:
      context: ./immobr
      dockerfile: Dockerfile
    image: nathanbahia/go-immobr-dev
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 60s ./immobr
    networks:
      - immobrnet
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nathanbahia/go-immobr-nginx-dev
    ports:
      - "80:80"
    networks:
      - immobrnet
    depends_on:
      - immobr 

  postgres:
    image: postgres:15.3-alpine3.18
    env_file:
      - ./.env
    ports:
      - "5432"
    networks:
      - immobrnet
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
